// https://www.tarot.com/tarot/decks
const tarotDecks = [
    ["https://gfx.tarot.com/images/site/decks/8-bit/full_size/0.jpg", "8-Bit Tarot Deck"],
    ["", "Wikimedia Commons Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/african/full_size/0.jpg", "African Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/angel/full_size/0.jpg", "Angel Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/apprentice/full_size/0.jpg", "Apprentice Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/aquarian/full_size/0.jpg", "Aquarian Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/archeon/full_size/0.jpg", "Archeon Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/art-nv/full_size/0.jpg", "Art Nouveau Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/art-of-life/full_size/0.jpg", "Art of Life Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cagliostro/full_size/0.jpg", "Cagliostro Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cary-yale-visconti/full_size/0.jpg", "Cary-Yale Visconti Tarocchi Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cat-people/full_size/0.jpg", "Cat People Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cats-eye/full_size/0.jpg", "Cat's Eye Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/celestial/full_size/0.jpg", "Celestial Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/chinese/full_size/0.jpg", "Chinese Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/chrysalis/full_size/0.jpg", "Chrysalis Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/classic/full_size/0.jpg", "Classic Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/connolly/full_size/0.jpg", "Connolly Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cosmic/full_size/0.jpg", "Cosmic Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cosmic-slumber/full_size/0.jpg", "Cosmic Slumber Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cosmic-slumber/full_size/0.jpg", "Cosmic Slumber Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/crowley/full_size/0.jpg", "Crowley Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/crows-magick/full_size/0.jpg", "Crow's Magick Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/crow/mid_size/0.jpg", "Crow Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/crystal-visions/full_size/0.jpg", "Crystal Visions Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/dark-exact/full_size/0.jpg", "Dark Exact Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/deviant-moon/full_size/0.jpg", "Deviant Moon Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/dragon/full_size/0.jpg", "Dragon Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/dreaming-way/full_size/0.jpg", "Dreaming Way Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/the-dreamkeepers-tarot/full_size/0.jpg", "Dreamkeepers Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/eight-coins-tattoo/full_size/0.jpg", "Eight Coins' Tattoo Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/english-magic/full_size/0.jpg", "English Magic Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/esoterico/full_size/0.jpg", "Esoterico Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/ethereal-visions/full_size/0.jpg", "Ethereal Visions Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/etteilla/full_size/0.jpg", "Etteilla Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/faerie-tarot/full_size/0.jpg", "Faerie Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/fantastical-creatures/full_size/0.jpg", "Fantastical Creatures Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/fantastical/full_size/0.jpg", "Fantastical Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/fenestra/full_size/0.jpg", "Fenestra Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/feng-shui/full_size/0.jpg", "Feng Shui Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/forest-folklore/full_size/0.jpg", "Forest Folklore Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/fradella/full_size/0.jpg", "Fradella Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/gendron/full_size/0.jpg", "Gendron Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/ghosts-spirits/full_size/0.jpg", "Ghosts & Spirits Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/gill/full_size/0.jpg", "Gill Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/goddess/full_size/0.jpg", "Goddess Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/golden-thread/full_size/0.jpg", "Golden Thread Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/gummybear/full_size/0.jpg", "Gummy Bear Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/haindl/full_size/0.jpg", "Haindl Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/halloween/full_size/0.jpg", "Halloween Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/roberts/full_size/0.jpg", "Hanson Roberts Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/heart-and-hands/full_size/0.jpg", "Heart & Hands Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/herbal/full_size/0.jpg", "Herbal Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/hermetic/full_size/0.jpg", "Hermetic Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/ibis/full_size/0.jpg", "Ibis Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/japaridze/full_size/0.jpg", "Japaridze Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/jolanda/full_size/0.jpg", "Jolanda Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/karma/full_size/0.jpg", "Karma Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/lovers-path/full_size/0.jpg", "Lovers Path Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/magic-manga/full_size/0.jpg", "Magic Manga Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/marseilles/full_size/0.jpg", "Marseilles Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/medicine-woman/full_size/0.jpg", "Medicine Woman Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/medieval-cat/full_size/0.jpg", "Medieval Cat Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/medieval-scapini/full_size/0.jpg", "Medieval Scapini Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/melanated/full_size/0.jpg", "Melanated Classic Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/merryday/full_size/0.jpg", "Merry Day Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/modern-medieval/full_size/0.jpg", "Modern Medieval Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/modern-witch/full_size/0.jpg", "Modern Witch Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/morgan-greer/full_size/0.jpg", "Morgan-Greer Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/motherpeace/full_size/0.jpg", "Motherpeace Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/mystic-mondays/full_size/0.jpg", "Mystic Mondays Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/napo/full_size/0.jpg", "Napo Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/new-century/full_size/0.jpg", "New Century Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/new-chapter/full_size/0.jpg", "New Chapter Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/old-english/full_size/0.jpg", "Old English Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/old-path/full_size/0.jpg", "Old Path Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/omegaland/full_size/0.jpg", "Omegaland Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/one-world/full_size/0.jpg", "One World Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/wirth/full_size/0.jpg", "Oswald Wirth Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/paulina/full_size/0.jpg", "Paulina Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/phantasma/full_size/0.jpg", "Phantasma Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/phantasmagoric/full_size/0.jpg", "Phantasmagoric Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/quick-easy/full_size/0.jpg", "Quick and Easy Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/renaissance/full_size/0.jpg", "Renaissance Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/rider/full_size/0.jpg", "Rider Waite Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/royal-thai/full_size/0.jpg", "Royal Thai Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/russian/full_size/0.jpg", "Russian Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/sacred-art/full_size/0.jpg", "Sacred Art Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/sacred-rose/full_size/0.jpg", "Sacred Rose Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/dali/full_size/0.jpg", "Salvador Dali Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/santa-fe/full_size/0.jpg", "Santa Fe Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/simplicity/full_size/0.jpg", "Simplicity Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/smith-waite/full_size/0.jpg", "Smith Waite Centennial Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/spiral/full_size/0.jpg", "Spiral Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/spiritsong/full_size/0.jpg", "Spiritsong Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/stairs/full_size/0.jpg", "Stairs Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/stars/full_size/0.jpg", "Stars Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/starter/full_size/0.jpg", "Starter Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/sun-moon/full_size/0.jpg", "Sun and Moon Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/1jj-swiss/full_size/0.jpg", "Swiss (1JJ) Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tapestry/full_size/0.jpg", "Tapestry Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-decoratif/full_size/0.jpg", "Tarot Decoratif Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-grand-luxe/full_size/0.jpg", "Tarot Grand Luxe Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-nuages/full_size/0.jpg", "Tarot Nuages Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-moon-garden/full_size/0.jpg", "Tarot of a Moon Garden Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-of-dreams/full_size/0.jpg", "Tarot of Dreams Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-of-mystical-moments/full_size/0.jpg", "Tarot of Mystical Moments Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-of-the-golden-wheel/full_size/0.jpg", "Tarot of the Golden Wheel Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-spirit/full_size/0.jpg", "Tarot of the Spirit Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/witches/full_size/0.jpg", "Tarot of the Witches Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/new-palladini-tarot/full_size/0.jpg", "New Palladini Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/ukiyoe/full_size/0.jpg", "Ukiyoe Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/universal-waite/full_size/0.jpg", "Universal Waite Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/vampire/full_size/0.jpg", "Vampire Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/vanessa/full_size/0.jpg", "Vanessa Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/visconti/full_size/0.jpg", "Visconti-Sforza Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/whimsical/full_size/0.jpg", "Whimsical Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/white-numen/full_size/0.jpg", "White Numen Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/winged-spirit/full_size/0.jpg", "Winged Spirit Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/zerner-farber/full_size/0.jpg", "Zerner Farber Tarot Deck"],
];