// https://www.tarot.com/tarot/decks
const tarotDecks = [
    ["https://gfx.tarot.com/images/site/decks/8-bit/full_size/0.jpg", "8-Bit Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/african/full_size/0.jpg", "African Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/angel/full_size/0.jpg", "Angel Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/apprentice/full_size/0.jpg", "Apprentice Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/aquarian/full_size/0.jpg", "Aquarian Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/archeon/full_size/0.jpg", "Archeon Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/art-nv/full_size/0.jpg", "Art Nouveau Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/art-of-life/full_size/0.jpg", "Art of Life Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cagliostro/full_size/0.jpg", "Cagliostro Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cary-yale-visconti/full_size/0.jpg", "Cary-Yale Visconti Tarocchi Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cat-people/full_size/0.jpg", "Cat People Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cats-eye/full_size/0.jpg", "Cat's Eye Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/celestial/full_size/0.jpg", "Celestial Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/chinese/full_size/0.jpg", "Chinese Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/chrysalis/full_size/0.jpg", "Chrysalis Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/classic/full_size/0.jpg", "Classic Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/connolly/full_size/0.jpg", "Connolly Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cosmic/full_size/0.jpg", "Cosmic Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cosmic-slumber/full_size/0.jpg", "Cosmic Slumber Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/cosmic-slumber/full_size/0.jpg", "Cosmic Slumber Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/crowley/full_size/0.jpg", "Crowley Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/crows-magick/full_size/0.jpg", "Crow's Magick Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/crow/mid_size/0.jpg", "Crow Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/crystal-visions/full_size/0.jpg", "Crystal Visions Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/dark-exact/full_size/0.jpg", "Dark Exact Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/deviant-moon/full_size/0.jpg", "Deviant Moon Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/dragon/full_size/0.jpg", "Dragon Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/dreaming-way/full_size/0.jpg", "Dreaming Way Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/the-dreamkeepers-tarot/full_size/0.jpg", "Dreamkeepers Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/eight-coins-tattoo/full_size/0.jpg", "Eight Coins' Tattoo Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/english-magic/full_size/0.jpg", "English Magic Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/esoterico/full_size/0.jpg", "Esoterico Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/ethereal-visions/full_size/0.jpg", "Ethereal Visions Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/etteilla/full_size/0.jpg", "Etteilla Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/faerie-tarot/full_size/0.jpg", "Faerie Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/fantastical-creatures/full_size/0.jpg", "Fantastical Creatures Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/fantastical/full_size/0.jpg", "Fantastical Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/fenestra/full_size/0.jpg", "Fenestra Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/feng-shui/full_size/0.jpg", "Feng Shui Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/forest-folklore/full_size/0.jpg", "Forest Folklore Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/fradella/full_size/0.jpg", "Fradella Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/gendron/full_size/0.jpg", "Gendron Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/ghosts-spirits/full_size/0.jpg", "Ghosts & Spirits Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/gill/full_size/0.jpg", "Gill Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/goddess/full_size/0.jpg", "Goddess Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/golden-thread/full_size/0.jpg", "Golden Thread Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/gummybear/full_size/0.jpg", "Gummy Bear Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/haindl/full_size/0.jpg", "Haindl Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/halloween/full_size/0.jpg", "Halloween Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/roberts/full_size/0.jpg", "Hanson Roberts Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/heart-and-hands/full_size/0.jpg", "Heart & Hands Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/herbal/full_size/0.jpg", "Herbal Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/hermetic/full_size/0.jpg", "Hermetic Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/ibis/full_size/0.jpg", "Ibis Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/japaridze/full_size/0.jpg", "Japaridze Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/jolanda/full_size/0.jpg", "Jolanda Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/karma/full_size/0.jpg", "Karma Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/lovers-path/full_size/0.jpg", "Lovers Path Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/magic-manga/full_size/0.jpg", "Magic Manga Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/marseilles/full_size/0.jpg", "Marseilles Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/medicine-woman/full_size/0.jpg", "Medicine Woman Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/medieval-cat/full_size/0.jpg", "Medieval Cat Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/medieval-scapini/full_size/0.jpg", "Medieval Scapini Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/melanated/full_size/0.jpg", "Melanated Classic Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/merryday/full_size/0.jpg", "Merry Day Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/modern-medieval/full_size/0.jpg", "Modern Medieval Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/modern-witch/full_size/0.jpg", "Modern Witch Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/morgan-greer/full_size/0.jpg", "Morgan-Greer Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/motherpeace/full_size/0.jpg", "Motherpeace Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/mystic-mondays/full_size/0.jpg", "Mystic Mondays Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/napo/full_size/0.jpg", "Napo Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/new-century/full_size/0.jpg", "New Century Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/new-chapter/full_size/0.jpg", "New Chapter Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/old-english/full_size/0.jpg", "Old English Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/old-path/full_size/0.jpg", "Old Path Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/omegaland/full_size/0.jpg", "Omegaland Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/one-world/full_size/0.jpg", "One World Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/wirth/full_size/0.jpg", "Oswald Wirth Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/paulina/full_size/0.jpg", "Paulina Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/phantasma/full_size/0.jpg", "Phantasma Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/phantasmagoric/full_size/0.jpg", "Phantasmagoric Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/quick-easy/full_size/0.jpg", "Quick and Easy Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/renaissance/full_size/0.jpg", "Renaissance Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/rider/full_size/0.jpg", "Rider Waite Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/royal-thai/full_size/0.jpg", "Royal Thai Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/russian/full_size/0.jpg", "Russian Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/sacred-art/full_size/0.jpg", "Sacred Art Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/sacred-rose/full_size/0.jpg", "Sacred Rose Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/dali/full_size/0.jpg", "Salvador Dali Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/santa-fe/full_size/0.jpg", "Santa Fe Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/simplicity/full_size/0.jpg", "Simplicity Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/smith-waite/full_size/0.jpg", "Smith Waite Centennial Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/spiral/full_size/0.jpg", "Spiral Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/spiritsong/full_size/0.jpg", "Spiritsong Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/stairs/full_size/0.jpg", "Stairs Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/stars/full_size/0.jpg", "Stars Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/starter/full_size/0.jpg", "Starter Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/sun-moon/full_size/0.jpg", "Sun and Moon Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/1jj-swiss/full_size/0.jpg", "Swiss (1JJ) Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tapestry/full_size/0.jpg", "Tapestry Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-decoratif/full_size/0.jpg", "Tarot Decoratif Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-grand-luxe/full_size/0.jpg", "Tarot Grand Luxe Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-nuages/full_size/0.jpg", "Tarot Nuages Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-moon-garden/full_size/0.jpg", "Tarot of a Moon Garden Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-of-dreams/full_size/0.jpg", "Tarot of Dreams Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-of-mystical-moments/full_size/0.jpg", "Tarot of Mystical Moments Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-of-the-golden-wheel/full_size/0.jpg", "Tarot of the Golden Wheel Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/tarot-spirit/full_size/0.jpg", "Tarot of the Spirit Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/witches/full_size/0.jpg", "Tarot of the Witches Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/new-palladini-tarot/full_size/0.jpg", "New Palladini Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/ukiyoe/full_size/0.jpg", "Ukiyoe Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/universal-waite/full_size/0.jpg", "Universal Waite Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/vampire/full_size/0.jpg", "Vampire Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/vanessa/full_size/0.jpg", "Vanessa Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/visconti/full_size/0.jpg", "Visconti-Sforza Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/whimsical/full_size/0.jpg", "Whimsical Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/white-numen/full_size/0.jpg", "White Numen Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/winged-spirit/full_size/0.jpg", "Winged Spirit Tarot Deck"],
    ["https://gfx.tarot.com/images/site/decks/zerner-farber/full_size/0.jpg", "Zerner Farber Tarot Deck"],
];

// https://www.astrology.com/article/order-of-tarot-cards/
const tarotNames = [
    'The Fool',
    'The Magician',
    'The High Priestess',
    'The Empress',
    'The Emperor',
    'The Hierophant',
    'The Lovers',
    'The Chariot',
    'Strength',
    'The Hermit',
    'Wheel of Fortune',
    'Justice',
    'The Hanged Man',
    'Death',
    'Temperance',
    'The Devil',
    'The Tower',
    'The Star',
    'The Moon',
    'The Sun',
    'Judgment',
    'The World',
    'Ace of Wands',
    'Two of Wands',
    'Three of Wands',
    'Four of Wands',
    'Five of Wands',
    'Six of Wands',
    'Seven of Wands',
    'Eight of Wands',
    'Nine of Wands',
    'Ten of Wands',
    'Page of Wands',
    'Knight of Wands',
    'Queen of Wands',
    'King of Wands',
    'Ace of Cups',
    'Two of Cups',
    'Three of Cups',
    'Four of Cups',
    'Five of Cups',
    'Six of Cups',
    'Seven of Cups',
    'Eight of Cups',
    'Nine of Cups',
    'Ten of Cups',
    'Page of Cups',
    'Knight of Cups',
    'Queen of Cups',
    'King of Cups',
    'Ace of Swords',
    'Two of Swords',
    'Three of Swords',
    'Four of Swords',
    'Five of Swords',
    'Six of Swords',
    'Seven of Swords',
    'Eight of Swords',
    'Nine of Swords',
    'Ten of Swords',
    'Page of Swords',
    'Knight of Swords',
    'Queen of Swords',
    'King of Swords',
    'Ace of Pentacles',
    'Two of Pentacles',
    'Three of Pentacles',
    'Four of Pentacles',
    'Five of Pentacles',
    'Six of Pentacles',
    'Seven of Pentacles',
    'Eight of Pentacles',
    'Nine of Pentacles',
    'Ten of Pentacles',
    'Page of Pentacles',
    'Knight of Pentacles',
    'Queen of Pentacles',
    'King of Pentacles'
];

const tarotMeaning = [
    'The Fool card in Tarot symbolizes new beginnings. The basic meaning of the card is that the Fool is on his way to a new beginning, and he has all he needs or wants as indicated by the bag on the staff. The Fool is shown in colorful clothes with a pack tied to his staff, a dog at his heels, and a cliff. The Tarot story of the Fool is that he travels aimlessly with all his worldly possessions. A daydreamer lost in his thoughts, he does not see the cliff and is likely to fall over. The dog at his heels tries to warn him.',
    'The Magician card in Tarot symbolizes male power of creation through willpower and desire. The Magician wears red and white clothes. The basic card symbols are the lemniscate (a figure eight on its side symbolizing eternal life and eternity), a small wand, a table displaying a chalice symbolizing knowledge and preservation, a pentacle, staff, and sword.',
    'The High Priestess card in Tarot symbolizes sexuality, mystery, and general higher power. The basic symbols of this card are blue, white, and black colors, pomegranates, an Isis moon crown, veil, solar cross, crescent moon, and pillars. The "B" stands for Boaz: negation and severity. The "J" stands for Jachin: beginning and mercy. The scroll is inscribed with the word "Tora," standing for either the Jewish Torah or an anagram of Tarot, with the last letter unseen.',
    'The Empress card in Tarot symbolizes Isis, motherhood, femininity, and fertility. The Empress is a creator of life, of romance, of art, of business, and here the idea gestates until it is ready to be born. The basic Tarot symbols for this card are the gown decorated with pomegranates, a crown of twelve six-pointed stars, a rod, a heart-shaped shield inscribed with the symbol for Venus, and a field of ripe wheat.',
    'The Emperor card in Tarot symbolizes accomplishment, confidence, wealth, stability, leadership, father/brother/husband, achievement, and a capable person. The basic symbols for this card are the throne, rams\' heads, and sometimes the eagle, orb, and scepter. The Emperor, as Aries (the Ram) is the infant, the first sign of the zodiac. He naturally follows the Empress.',
    'The Hierophant card in Tarot symbolizes traditional values and is often associated with the religious or spiritual. The purpose of the Hierophant is to bring the spiritual down to earth. The basic meaning of this Tarot card is to create harmony in the face of crisis. During a crisis, the Hierophant diffuses the panic and offers good and practical advice. The basic symbols of the Hierophant card are twin pillars, a staff, throne, the triple crown of a pope, a hand raised in blessing, and two acolytes.',
    'The Lovers card in Tarot symbolizes (you guessed it) love, as well as romance, connection, attraction, and perfect harmony. The basic symbols of this card are an angel or Cupid, a man and a woman, and two trees. In some decks, there is a man standing between two women, and in some decks, one tree is flowering and the other has fruit. The Waite Tarot cards have Adam and Eve, one tree, a serpent, and apples.',
    'The Chariot card in Tarot is not an easy card to interpret. It could mean an eventual hard-won success. The card often pictures the chariot, an armored warrior, sun or moon symbols, the encircled rod on the winged shield, black and white sphinxes (or lions or horses), sometimes at rest. Some decks have a canopy of stars and sometimes a throne inside the chariot.',
    'The Strength card in Tarot is about energy and courage. It is a card of bravery and fierceness, much like a lion\'s hot and roaring energy. In addition, it also symbolizes an unafraid woman. She is undaunted, indomitable, and steadfast. The basic symbols of the Strength card are a woman with a lemniscate (a figure eight on its side symbolizing eternal life and eternity) hovering over her head, a lion, and a chain of roses.',
    'The Hermit card in Tarot is a card of introspection, soul searching, analysis, and self-reflection. It denotes that this is not a time of socializing or action but of peace and solitude. The basic symbol of this card is a robed man or monk with a staff and carrying a lantern. The landscape is barren.',
    'TODO - Wheel of fortune',
    'The Justice card in Tarot is about reason, truth, and, yes, justice. This is the card about cold, objective balance. It\'s also about moderation in all things, as well as the realities of karma. If you\'re not keeping the scales balanced, there could be some fallout. The basic symbols of this card include a judge-like figure, sometimes blindfolded, either sitting or standing, with scales in his left hand and an upraised sword in the other hand.',
    'The Hanged Man card in Tarot symbolizes trial or meditation, selflessness, and sacrifice. The basic symbols of this card are a man hanging by one foot from a tau cross. His free leg is always crossed to form a "4" and his face is always peaceful. His hands may be either tied or dangling. At times, some coins may be falling from his hands or pockets.',
    'The Death card in Tarot is a card of major transformation and new beginnings, and it probably won\'t be easy. The Death card meaning in a Tarot reading is about transformation, passage, and change. The basic symbols of the Death card are Death as a skeleton in black robes or armor. There may also be a scythe or a flag featuring a five-petaled rose. There may be other figures in the field, the most common and recurring is that of a child.',
    'The Temperance card in Tarot can be difficult to interpret, but in general it\'s about the blending of opposites and the achieving of synthesis. It\'s about harmony, peace, and patience. The basic symbols of the Temperance card are an angel (often female, but sometimes genderless), a pool of water or river, and two cups with fluid flowing between them. It\'s a serene, peaceful scene of harmonious beauty.',
    'The Devil card in Tarot is about ambitions and is also synonymous with temptation, addiction, and depression. The basic symbols of this card are a winged and horned Devil on a black pedestal, naked male and female figures, chains, and an inverted pentagram.',
    'The Tower card in Tarot is all about the downfall of old ideas. A structure has suddenly and violently come crashing down, leading to chaos and distress, but it has also made room for something new to be built. The basic symbols of this card are a tower on a rocky outcrop, a bolt of lightning, a couple of figures falling from the tower, and waves crashing below.',
    'The Star card in Tarot symbolizes the future, clarity of vision, and spiritual insight. The basic symbols of this card are seven or eight stars, a pool of water, a kneeling woman (one foot in the water, the other on land), and two urns.',
    'The Moon card in Tarot symbolizes that things might be amiss and that you can\'t trust your first impression. Things are not how they seem. The basic card symbols are a full moon (with a crescent within), twin pillars, a dog and a wolf howling, a stream that runs to the ocean, and a crayfish emerging from the water.',
    'The Sun card in Tarot radiates positive energy. This is one of the most optimistic cards, indicating enthusiasm and joie de vivre.',
    'TODO - JUDGMENT',
    'The World card in Tarot is a wonderful card, representing a successful conclusion after all aspects have been accounted for. Things have come full circle. A journey has been completed, and a long-term project has come to an end. The basic symbols of this card are a dancing woman or hermaphrodite, a wreath in the shape of a yoni (almond-shaped circle), two wands, a cherub, eagle, lion, and bull.',


    'The Ace of Wands in Tarot represents creative force, enthusiasm, and courage. The Ace of Wands meaning in a Tarot reading is one of constructive, confident energy working toward individual power and fulfillment.',
    'The Two of Wands in Tarot represents personal power, boldness, and originality. It stands for individual courage and greatness. Tapping the same source of energy as that of the Magician of the Major Arcana, the Two of Wands stands for personal power brought down to earth. The Two of Wands also stands for planning and preparation.',
    'The Three of Wands in a Tarot reading stands for exploration, foresight, leadership, and opportunity.',
    'The Four of Wands in Tarot stands for celebration, freedom, and excitement. It\'s all about prosperity and partnerships, and it represents events that generate excitement. The excitement and celebration could be unexpected and come as a surprise. At times, the appearance of the Four of Wands in a reading represents a planned celebration, such as a wedding or anniversary. These events and celebrations leave you with a feeling of joy. The excitement is that of the little child, which still exists in all adults, just waiting to come out. It is the excitement of the child upon seeing a birthday cake lit with candles, the child waiting for a turn on the roller coaster. The Four of Wands also stands for freedom, which can take many forms.',
    'The Five of Wands in Tarot stands for scuffles, strife, challenges, disagreements, competition, and hassles. Nothing seems to be flowing smoothly, and it appears as though everything is against you. It seems nothing is coordinated, everyone is working at cross-purposes, and the ride is going to get bumpier and bumpier. Of course, these are all small and irritating obstacles, and there are no major blocks. Other than hassles and disagreements, the card also stands for competition. In the right circumstances, competition is fine. It generates the encouragement to do one\'s best.',
    'The Six of Wands in Tarot represents triumph, acclaim, and pride. This card is the equivalent of the Chariot of the Major Arcana. Just like the Chariot, it represents moments of victory and triumph. Some of the cards that reinforce the qualities of the Six of Wands are the Chariot and the Sun (Major Arcana cards) and the Nine of Cups. Some cards that oppose the Six of Wands are the Tower (Major Arcana card) and the Five of Pentacles, Five of Cups, and Ten of Swords.',
    'The Seven of Wands in Tarot stands for defiance, defense, aggression, conviction, and valor. Aggression and defiance are both represented by the Seven of Wands as two sides of the same coin. Some of the cards that reinforce the qualities of the Seven of Wands are the Five of Wands, Nine of Wands, and Five of Swords. Some cards that oppose the Seven of Wands are the High Priestess and Hanged Man (Major Arcana cards) and the Three of Pentacles.',
    'The Eight of Wands in Tarot stands for communication, travel, and speed. The Eight of Wands represents quick action, conclusion, and news. The wands on this card are an indication of action and the effects of that action. Normally, before we act, we think about it, we imagine, contemplate, talk, and dream. We then decide to put our ideas into action. Some of the cards that reinforce the qualities of the Eight of Wands are the Magician, Wheel of Fortune, and Death (Major Arcana cards), and the Eight of Cups. Some cards that oppose the Eight of Wands are the High Priestess (Major Arcana card), the Seven of Pentacles, and the Four of Swords.',
    'The Nine of Wands in Tarot stands for defensiveness, perseverance, stamina, resilience, and resistance. A look at the figure on the Nine of Wands card shows that he has been through certain battles. The figure is bandaged on his head and arm and supported by a crutch. He might be hurt, but he is not down, He is still standing! Because he\'s hurt, he may become defensive. Some of the cards that reinforce the qualities of the Nine of Wands are Strength (Major Arcana card) and the Seven of Wands, Two of Swords, and Eight of Pentacles. Some cards that oppose the Nine of Wands are the Three of Cups, Six of Cups, and Eight of Cups.',
    'The Ten of Wands in Tarot stands for overextending, overwork, burdens, oppression, and struggle. Some of the cards that reinforce the qualities of the Ten of Wands are Justice (Major Arcana card) and the Five of Wands, Six of Swords, Nine of Swords, and Five of Pentacles. Some cards that oppose the Ten of Wands are the Fool and Hanged Man (Major Arcana cards) and the Four of Wands, Four of Swords, and Seven of Swords.',
    'The Page of Wands in Tarot stands for being creative, enthusiastic, confident, and courageous. This card also considers spiritual concepts. Depending on the accompanying cards, at times the Page of Wands may further imply that the entire situation is immersed in the spirit of excitement and adventure. Again, depending on the circumstances, the Page of Wands can also suggest a presence of a young-at-heart adult or a child with whom you would interact. Such interactions may involve independence, high energy, risky behavior, or shared enthusiasm.',
    'The Knight of Wands in Tarot stands for being charming (superficial), self-confident (cocky), daring (foolhardy), adventurous (restless), and passionate (hot-tempered). Where on the one hand, the Knight of Wands is full of energy and never seems to be afraid to try new things. On the other hand, he seems too sure of himself and his abilities. Although others may be baffled by his crazy stunts, his courage and passion are still admired. The Knight of Wands tends to be shallow, and one can\'t expect deep commitment from him. He is reckless and irresponsible and acts without thinking. This gets him into trouble. The Knight of Wands also delivers spiritual messages.',
    'The Queen of Wands in Tarot stands for being attractive, wholehearted, energetic, cheerful, and self-assured. Her personality is a combination of the positive fire energy of all the Wands suit, and the inward focus of a Queen. The Queen of Wands is always attractive and good-looking. She has an easygoing manner, and this and her warm smile attract a lot of friends and admirers. She tackles all tasks, no matter what, with complete dedication, and her energy and enthusiasm are contagious.',
    'The King of Wands in Tarot stands for being creative, inspiring, forceful, charismatic, and bold. His personality is a combination of the positive fire energy of the Wands suit and the outward focus of a King. He is enthusiastic and creative, and he allows his originality and inspiration to take form. If an opportunity presents itself, he takes the lead. The King of Wands is forceful when pursuing his goals, and others follow. Unless it suits his purpose, the King of Wands is never a passive observer. He jumps in to create results. Never the one to be quiet, he is dramatic and exciting and often the center of attraction. The King is bold and daring, and he has the energy and self-assurance to take risks. He believes in himself, has the courage of his convictions, and often avoids safe and easy routes.',


    'The Ace of Cups in Tarot stands for deep feelings, intuition, intimacy, and love. The Ace of Cups meaning in a Tarot reading is that emotional awareness has come into your life. This awareness could take any form, such as an attraction, strong feeling, or sympathetic reaction. It could also offer an opportunity, gift, or encounter.',
    'The Two of Cups in Tarot symbolizes the beauty and power of the sexual attraction between two people. This is the card couples want to be dealt. This card also represents the union of any two entities. There is always a potential for bonding whenever two forces are drawn together, whether it\'s people, groups, ideas, or talents. This is the deeper meaning of this card.',
    'The Three of Cups in Tarot stands for exuberance, friendship, and community. The Three of Cups meaning in a Tarot reading is coming together in love. It comes from the viewpoint of emotions, such as feelings you have when joining with others, whether that\'s a friendship or a community. The image shows three women dancing with their arms reaching out to connect their feelings and emotions, as symbolized by the cups. The women represent the social glue that binds everyone together. The card stands for emotions and experiences that make you feel like dancing, singing, and rejoicing.',
    'The Four of Cups in Tarot stands for self-absorption, apathy, and going within. The Four of Cups meaning in a Tarot reading is that you should be cautious about getting stuck in self-absorption. A self-absorbed person refers only to his or her own interests and desires, just like the figure on the Four of Cups card. The figure is unaware of the cup being offered to him. As he is so turned inward within himself that he misses a precious gift.',
    'The Five of Cups in Tarot stands for loss, bereavement, and regret. The Five of Cups meaning in a Tarot reading is related to tangible losses, such as money, possessions, relationship, and work. Or the losses could be intangible, such as dreams, opportunities, prospects, or reputation. The loss, the sorrow, the regret could be great or small. That said, you shouldn\'t be discouraged by the appearance of this card because every negative has a positive side to it. The figure on the Five of Cups card is draped in black and covered in grief. He is staring at the overturned cups in front of him, oblivious to the fact that there are two upright cups behind him. Loss always hurts because we always resist change. However, every loss opens new opportunities and possibilities for growth. Every loss initiates a change. We need to go with the flow. If we struggle to hold on to what is gone, we suffer more.',
    'The Six of Cups in Tarot stands for goodwill, caring, innocence, and childhood. The Six of Cups meaning in a Tarot reading is simple goodness. Yes, there\'s a lot of violence, anger, and dishonesty in the world, but the opposite is true, too. This is what the Six of Cups represents, and it encourages you to be kind, forgiving, and generous. Lend your car to a friend or fill in for a sick co-worker. These small gestures are important.',
    'The Seven of Cups in Tarot stands for wishful thinking, options, impracticality, sloppiness, and dissipation. The Seven of Cups meaning in a Tarot reading is that it\'s time to make a decision and be realistic about what you can do and how far you can extend yourself. The Seven of Cups provides balance to the efficiency, neatness, time management, and all things controlled and in order. Those things have their place, but sometimes you need to let go.',
    'The Eight of Cups in Tarot stands for deeper meaning, moving on, and weariness. The figure on the card is a man leaving on a journey, striking out on a new path. The card means that change could come in many forms. It could be physical, such as a job change, relocation, or change in relationships. Change could also refer to inner changes, such as replacing older patterns of thought with new ones.',
    'The Nine of Cups in Tarot stands for wish fulfillment, satisfaction, and sensual pleasure. The Nine of Cups is also known as the Wish Card in certain Tarot traditions. The tone of the Nine of Cups card is smugness, that feeling the cat gets when it manages to catch the canary! The figure on the Nine of Cups card is a man with contentment written all over him. He sits confidently, arms folded, with a smiling face. He seems to exude happiness, and he looks as though he has everything he ever wanted. He seems to say that he could not be happier.',
    'The Ten of Cups in Tarot stands for joy, peace, and family. The Ten of Cups in a Tarot reading is a sign that it\'s a time of blessings, it is time for the fulfillment one richly deserves, and that it will come. The image on the Ten of Cups card is that of a happy and loving couple with children. Further, there is a home in the background, surrounded by trees and water. This is what your emotional life could be at its best. The image represents an ideal that is within reach.',
    'The Page of Cups card in Tarot stands for being emotional, intuitive, intimate, and loving. The Page of Cups meaning in a Tarot reading is to let your feeling show, to be sentimental or romantic, and to respond to beauty. It is the time to shed your detachment and let your heart lead the way! To be intuitive, you need to receive guidance from within. You need to trust your gut reaction and act on a hunch. To be intuitive, you need to have a psychic experience. Being intimate is another aspect of the Page of Cups card. Being intimate is having special moments of togetherness, sharing something special. Being intimate is solidifying a friendship, getting closer to someone, and starting or renewing a love affair. It is the time to feel free and express your feelings.',
    'The Knight of Cups in Tarot stands for being romantic, imaginative, and sensitive. The Knight of Cups meaning in a Tarot reading can also be somewhat moody and temperamental, but also a thing of great beauty, both the creation of beautiful things and the appreciation of them. It is charm, affection, and big, big emotions.',
    'The Queen of Cups in Tarot stands for being loving, tenderhearted, intuitive, psychic, and spiritual. The Queen of Cups meaning in a Tarot reading is a combination of the positive water energy of all the Cups and the inward focus of a Queen. She always has a loving and sensitive nature. She never reacts with impatience or anger, and she has a kind word for everyone. She is compassionate and lets her heart lead the way. The Queen is more open to her inner knowledge and trusts her intuition. She reveres all aspects of the divine\'s creation, loves and embraces everyone, and is moved by the tragedies and beauties of life.',
    'The King of Cups in Tarot stands for wisdom, calm, diplomacy, caring, and tolerance. The King of Cups meaning in a Tarot reading is a combination of the positive water energy of the Cups suit and the outward focus of a king. His knowledge of the world comes from his heart. Wise and understanding, he guides his students lovingly. In all situations, he is calm and relaxed, and he knows intuitively what is required at any given moment. His persona exudes peacefulness, and everyone turns to him for advice as he listens attentively. Under him, all others have the freedom to grow and develop in their own way.',

    'The Ace of Swords in Tarot stands for mental force, truth, justice, new ideas and plans, victory, and fortitude. The Ace of Swords meaning in a Tarot reading is one of difficulties being met with intelligence and clear thinking.',
    'The Two of Swords in Tarot stands for blocked emotions, avoidance, and stalemate. The Two of Swords meaning in a Tarot reading is one of balancing hard choices and making difficult decisions. The card symbolizes the woman\'s struggle to keep her feelings within herself and fending off outside approaches.',
    'The Three of Swords in Tarot stands for heartbreak, loneliness, and betrayal. The Three of Swords meaning in a Tarot reading could be one of heartbreak, real grief, or seemingly infinite sadness.',
    'The Four of Swords in Tarot stands for rest, contemplation, and quiet preparation. All the Swords cards represent some form of trials and challenges, and the Four of Swords is no different. It is a challenge to remain quiet.',
    'The Five of Swords in Tarot stands for self-interest, discord, hostility, aggression, and dishonor. The Five of Swords meaning in a Tarot reading can also indicate total self-interest: It\'s all about "I" and "me." It can also mean giving up, walking out, or being stressed or amid conflict.',
    'The Six of Swords in Tarot stands for the blues, recovery, and travel. It represents pushing through a rough sea to reach calmer waters.',
    'The Seven of Swords in Tarot stands for running away, lone wolf style, and hidden dishonor. The Seven of Swords represents someone who has secret and solitary plans.',
    'The Eight of Swords in Tarot stands for restriction, confusion, and powerlessness. The woman on the card is blindfolded, tightly bound, and caught in a prison formed by the surrounding swords. She is unaware of where her security lies.',
    'The Nine of Swords in Tarot stands for worry, guilt, and anguish. It represents the pain and anguish we generate within ourselves, unlike the Three of Swords where people outside are responsible for the pain and betrayal. The Nine of Swords meaning in a Tarot reading is often one of fear and anxiety.',
    'The Ten of Swords in Tarot stands for martyrdom, a victim mentality, and bottoming out. The Ten of Swords meaning in a Tarot reading is one of deep loss, painful betrayal, and sad events.',
    'The Page of Swords in Tarot stands for being truthful and just, using your mind, and having fortitude. At times, the Page of Swords is representative of a child or a young-at-heart adult.',
    'The Knight of Swords in Tarot stands for being direct (blunt), authoritative (overbearing), incisive (cutting), knowledgeable (opinionated), and logical (unfeeling). On the one hand, the Knight of Swords has a keen intellect, speaks clearly with authority, and is a master of logic. On the other, he can be tactless, convinced of his own superiority, and undiplomatic. He can be relied on for his analytical lucidity. Being indifferent to the feelings of others, he does not tolerate stupidity.',
    'The Queen of Swords in Tarot stands for honesty, astuteness, forthrightness, wittiness, and experience. Her personality is a combination of the positive air energy of the Swords suit and the inward focus of a Queen. The Queen of Swords admires honesty, is committed to truth, and tells you exactly as it is. She has no interest in lies or tricks and has a marked lack of pretense. She fully understands the good and the bad of the world and is not easy to fool. She can easily analyze a situation, and she can identify a tricky one coming at her. Her observations are straightforward and candid and not meant to be hurtful. Another of the traits of the Queen of Swords is a sense of humor along with witty comebacks.',
    'The King of Swords in Tarot stands for being intellectual, analytical, articulate, just, and ethical. He is quite eloquent and insightful. His personality is a combination of the positive air energy of the Swords suit and the outward focus of a King. He is an intellectual and can assimilate all kinds of information. He handles all situations fairly and honorably and renders impartial and just decisions. He is highly ethical and incorruptible, and he expects others to live by the same standards. He is quick to work out solutions and equally good at explaining them to others. The King of Swords has the ability to move forward by cutting through the confusion and providing clarity. In this manner, he takes care of any and all chaotic conditions.',

    'The Ace of Pentacles in Tarot stands for material force, prosperity, practicality, and trust. It signifies possibility where abundance and security are concerned. The Ace of Pentacles meaning in a Tarot reading is one of new beginnings.',
    'The Two of Pentacles in Tarot stands for flexibility, fun, and juggling. The Two of Pentacles meaning in a Tarot reading is high energy. The card symbolizes fun and good times, but be careful of overstimulation. The figure on the card is a young man juggling and dancing simultaneously. The two pentacles within the loop of infinity indicate that he can handle all problems and juggle his worldly concerns away. He can easily control the ups and downs of his life as symbolized by the two ships riding the waves in the background.',
    'The Three of Pentacles in Tarot stands for teamwork, planning, and competence. The Three of Pentacles meaning in a Tarot reading is about overcoming the impossible. This card is one of three cards in the Tarot deck that focus on the group, the others being the Three of Cups and the Hierophant of the Major Arcana.',
    'The Four of Pentacles in Tarot stands for possessiveness, control, and blocked change. The Four of Pentacles meaning in a Tarot reading is the desire to control, the desire to impose one\'s will on another. A word of caution: Make sure your need for control doesn\'t get out of hand. This can lead to a stifling of creativity and individual expression.',
    'The Five of Pentacles in Tarot stands for hard times, ill health, and rejection. The Five of Pentacles meaning in a Tarot reading is usually negative. The image on the Five of Pentacles card of two cold, hungry, and sick figures is self-explanatory. The suffering portrayed in the card is easily recognizable: people without life\'s basic necessities. But there is also a spiritual component to all this. Remember that all setbacks are temporary, and comfort may be around the corner.',
    'The Six of Pentacles in Tarot stands for having or not having resources, knowledge, and power. The Six of Pentacles meaning in a Tarot reading is difficult to interpret. It falls between the extremes of having and not having. The image on the Six of Pentacles card is of a rich person giving away coins to one beggar while another is waiting his turn. The person is holding the scales of justice in one hand as if to decide who gets coins and who doesn\'t. The picture is very clear about who is in charge and who is not, as well as who has and who has not.',
    'The Seven of Pentacles in Tarot stands for assessment, reward, and change of direction. The Seven of Pentacles meaning in a Tarot reading is a time-out. This isn\'t a card of finality. This is an in-between card that means you have to pause and check your strategy. The image on the card is a person who has worked hard and then paused to take some time to admire their work.',
    'The Eight of Pentacles in Tarot stands for diligence, knowledge, and detail. The Eight of Pentacles meaning in a Tarot reading is hard work, attention to detail, and focus. The person on the card seems busy in a project that\'s taking up all his attention. He has isolated himself to concentrate on the job at hand.',
    'The Nine of Pentacles in Tarot stands for discipline, self-reliance, and refinement. The Nine of Pentacles meaning in a Tarot reading is positive. It\'s about not concentrating too much on the business side of life, represented by coins in the image that are placed toward the ground. On the other hand, there is another side to life: the arts, music, and the other forms of beauty that are very much part of our lives. You have to enjoy these finer things, too.',
    'The Ten of Pentacles in Tarot stands for affluence, permanence, and convention. The Ten of Pentacles meaning in a Tarot reading is material success. The image on the card is a marketplace in a village with people going about their everyday lives. This is a sign of convention and permanence. The luxuriously robed older person patting his dogs and the coins all around signify affluence.',
    'The Page of Pentacles in Tarot stands for being practical, prosperous, trusting, and trustworthy, and having an effect. The Page of Pentacles meaning in a Tarot reading is about opportunity.',
    'The Knight of Pentacles in Tarot stands for being unwavering, cautious, thorough, realistic, and hardworking. The Knight of Pentacles meaning in a Tarot reading is that, on the one hand, the Knight of Pentacles is hardworking, with tremendous stamina and high dedication, and on the other hand, he may be obsessive about little details and stubborn, refusing to admit he\'s wrong. The Knight of Pentacles is prudent and never wasteful. He is inflexible, he does not like change of any kind, and he sometimes can take the gloomiest view. He\'s a pessimist, though he would call himself a realist.',
    'The Queen of Pentacles in Tarot stands for nurturing, bigheartedness, resourcefulness, and trustworthiness. The Queen of Pentacles meaning in Tarot is that something needs to be done, and she\'s here to help make it happen. Her personality is a combination of the positive earth energy of the Pentacles suit and the inward focus of a Queen. She is warm and generous, and she takes great pleasure in caring for and nurturing others. Sensible and practical, she ensures everyone is happy and secure. The Queen of Pentacles is always ready to calm your fears and share all your troubles.',
    'The King of Pentacles in Tarot stands for being enterprising, adept, reliable, supportive, and steady. His personality is a combination of the positive earth energy of the Pentacles suit and the outward focus of the King. The King of Pentacles meaning in a Tarot reading is that he succeeds in whatever he sets out to do; in fact, he has the "golden touch" attributed to King Midas. He is the jack-of-all-trades and the master of all that he does. He is competent, he is enterprising, he is adept, and he can draw on his vast range of practical knowledge. Best of all, he is dependable and acts with extreme responsibility. Others rely on him, and he gives his support whenever required. He pursues all his goals firmly and with resolve, lends stability to all situations, and is steadfast until he is successful.',
];

const tarotVideos = [
    'https://www.youtube.com/embed/6ANCC8GNXNg',
    'https://www.youtube.com/embed/rRKvpyF1A-4',
    'https://www.youtube.com/embed/5Jv1MwHqZt0',
    'https://www.youtube.com/embed/38jppRf6Kf8',
    'https://www.youtube.com/embed/9doGpwfmzsU',
    'https://www.youtube.com/embed/aQ2J5nSoYHA',
    'https://www.youtube.com/embed/MaUpFiRB8qE',
    'https://www.youtube.com/embed/gmjWvIqm1zY',
    'https://www.youtube.com/embed/zt3XkdOYLz4',
    'https://www.youtube.com/embed/YFxfCFbxYtk',
    'https://www.youtube.com/embed/F1_QQ9PtfX8',
    'https://www.youtube.com/embed/2mHYVQjDKY8',
    'https://www.youtube.com/embed/-QoU_L2f7UI',
    'https://www.youtube.com/embed/ShariS-UYMk',
    'https://www.youtube.com/embed/xOOngjEzP9M',
    'https://www.youtube.com/embed/VFRCxmrv4EU',
    'https://www.youtube.com/embed/M64EWIF2LKs',
    'https://www.youtube.com/embed/TE-JzokRr7w',
    'https://www.youtube.com/embed/VoWoWFT3jYQ',
    'https://www.youtube.com/embed/8lAzB6_yWQ4',
    'https://www.youtube.com/embed/npfvVxCAhc0',
    'https://www.youtube.com/embed/_69qMMqok6c',

    'https://www.youtube.com/embed/AUNyhGQEjO0',
    'https://www.youtube.com/embed/Gxl4yrMe89U',
    'https://www.youtube.com/embed/LSFGUoHCI9E',
    'https://www.youtube.com/embed/x9I_K3CI-h0',
    'https://www.youtube.com/embed/C5GPxObl9Is',
    'https://www.youtube.com/embed/GDgRXmxAV9A',
    'https://www.youtube.com/embed/tc6_U14n9E0',
    'https://www.youtube.com/embed/prBrw4KnDyA',
    'https://www.youtube.com/embed/g77O5X5hPzo',
    'https://www.youtube.com/embed/iKGpoT6ZT1o',
    'https://www.youtube.com/embed/T41o2G9zsI4',
    'https://www.youtube.com/embed/eyWkHkiNE5M',
    'https://www.youtube.com/embed/7HT1rkRGjlE',
    'https://www.youtube.com/embed/261SLzHcxgk',


    'https://www.youtube.com/embed/vCTK14qjLCo',
    'https://www.youtube.com/embed/d1v0x1HOQlQ',
    'https://www.youtube.com/embed/xgccbjakcuM',
    'https://www.youtube.com/embed/pk0UT8UtOsI',
    'https://www.youtube.com/embed/q4sNkZrFM_M',
    'https://www.youtube.com/embed/9p5Q26vyj3E',
    'https://www.youtube.com/embed/DVrfEbsTX7o',
    'https://www.youtube.com/embed/J_8HocR6Ka8',
    'https://www.youtube.com/embed/L4O-YDNSOac',
    'https://www.youtube.com/embed/g0D9KAkcLsM',
    'https://www.youtube.com/embed/hC3jrtrssG0',
    'https://www.youtube.com/embed/mvlvhKPxyVY',
    'https://www.youtube.com/embed/_y-SVHNXteQ',
    'https://www.youtube.com/embed/e3yqH_JO_dA',

    'https://www.youtube.com/embed/7Jtkuurbvhs',
    'https://www.youtube.com/embed/6Kv_v9xYaI4',
    'https://www.youtube.com/embed/9kmonSlDurE',
    'https://www.youtube.com/embed/cEomQXshCps',
    'https://www.youtube.com/embed/UP0QSVdGfTQ',
    'https://www.youtube.com/embed/QiuMD0DQsAs',
    'https://www.youtube.com/embed/GfkUL9stiQI',
    'https://www.youtube.com/embed/ZJh6aM1QI_Y',
    'https://www.youtube.com/embed/00xtLoRzVrw',
    'https://www.youtube.com/embed/fRJMEPxkQNU',
    'https://www.youtube.com/embed/1isOxY3apRU',
    'https://www.youtube.com/embed/xwX3Y5Ima0U',
    'https://www.youtube.com/embed/NmNNxaDdZYg',
    'https://www.youtube.com/embed/6zt1hOB6rDc',

    'https://www.youtube.com/embed/ybw8xov7J1U',
    'https://www.youtube.com/embed/wrk6S9jpXDc',
    'https://www.youtube.com/embed/hpO0_iFAysc',
    'https://www.youtube.com/embed/Cw40_iEq6MA',
    'https://www.youtube.com/embed/ZNOWs7ovUZM',
    'https://www.youtube.com/embed/kU_TO03FwKc',
    'https://www.youtube.com/embed/YtWACiQuiaA',
    'https://www.youtube.com/embed/_xNlZprv11o',
    'https://www.youtube.com/embed/coKY9FHUN40',
    'https://www.youtube.com/embed/PuJLXXYBXsA',
    'https://www.youtube.com/embed/RGrTUuUJLpE',
    'https://www.youtube.com/embed/QzzCvi2WyeI',
    'https://www.youtube.com/embed/trLemY26XlA',
    'https://www.youtube.com/embed/X0-SBHg46Dc',


    '',
    '',
    '',
];