const shorts4 = [
    'Beginnings',
    'Turning visions into reality',
    'Intuition',
    'Fertility',
    'Strategic planning',
    'Traditions',
    'Partnership',
    'Goal',
    'Strength',
    'Introspection',
    'Wheel',
    'Cause and effect',
    'One option to wait',
    'Rebirth',
    'Balance',
    'Addiction',
    'Ruin',
    'Hope',
    'Unseen problems',
    'Success',
    'Exam',
    'Completion',

    'Inspiration',
    'Planning',
    'Expansion',
    'Homecoming',
    'Competition',
    'Victory',
    'Self-defence',
    'Speed',
    'Persistence',
    'Stress',
    'New project',
    'Creativity',
    'Confidence',
    'Power',

    'New relationship',
    'Romance',
    'Friendship',
    'Apathy',
    'Abandonment',
    'Nostalgia',
    'Self-delusion',
    'Retreat',
    'Jubilance',
    'Fulfillment',
    'New love',
    'Princess Charming',
    'Support',
    'Empathy',

    'New ideas',
    'Decision',
    'Heartbreak',
    'Contemplation',
    'Mental battle win',
    'Paradigm shifting',
    'Mental cheating',
    'No ideas',
    'Run out of ideas',
    'Mental loss',
    'Curious kid',
    'Fast-talking person',
    'A self sufficient person',
    'Strategic thought',

    'New income',
    'Two choices',
    'Teamwork',
    'Greed',
    'Loss',
    'Generosity',
    'Patience',
    'Mastering',
    'Luxury',
    'Legacy',
    'A patient kid',
    'Reliable person',
    'A resourceful person',
    'Practical leader'
];