// https://daily-tarot-girl.com/tarot-card-meanings/list-of-tarot-card-meanings/
const shorts = [
    'New beginnings, optimism, trust in life',
    'Action, the power to manifest',
    'Inaction, going within, the mystical',
    'Abundance, nurturing, fertility, life in bloom!',
    'Structure, stability, rules and power',
    'Institutions, tradition, society and its rules',
    'Sexuality, passion, choice, uniting',
    'Movement, progress, integration',
    'Courage, subtle power, integration of animal self',
    'Meditation, solitude, consciousness',
    'Cycles, change, ups and downs',
    'Fairness, equality, balance',
    'Surrender, new perspective, enlightenment',
    'The end of something, change, the impermeability of all things',
    'Balance, moderation, being sensible',
    'Destructive patterns, addiction, giving away your power',
    'Collapse of stable structures, release, sudden insight',
    'Hope, calm, a good omen!',
    'Mystery, the subconscious, dreams',
    'Success, happiness, all will be well',
    'Rebirth, a new phase, inner calling',
    'Completion, wholeness, attainment, celebration of life',

    'New beginnings, creative spark, fertile ideas',
    'Contemplation, assessing ones life direction',
    'Reaping the rewards of your efforts',
    'Celebration, safety, the home',
    'Competition, minor struggles or disagreements',
    'Success, accolades and achievement',
    'Feeling defensive and on guard',
    'Speed, things manifesting quickly',
    'Pessimism, gearing up for the worst',
    'Feeling oppressed, exhaustion, too many responsibilities',
    'Newly inspired, excited about life and work',
    'An adventurous risk taker who follows his passions',
    'Confidant, focused, has zest for life',
    'Career focused, mature, passionate',

    'Emotional fulfillment, joy',
    'Partnership, mutual attraction, compatibility',
    'Celebration, fun with friends, laughter',
    'Boredom, dissatisfaction with what is being offered',
    'Dwelling on the negative, self pity',
    'Sentimentality, kindness, help',
    'So many choices! Indecision, getting lost in fantasy',
    'Abandoning something in search of something better',
    'Indulgence, self-satisfaction',
    'Emotional bliss, happiness, attainment',
    'Creative, inspired, learning artistic skill',
    'Romantic, adventurous, following one’s heart',
    'Emotionally nurturing, intuitive, sensitive',
    'Need to acknowledge deep feelings, avoid drowning out emotions',

    'A fresh start, a sudden opportunity or idea, clarity',
    'Indecision',
    'Heartbreak, betrayal',
    'Meditation, rest, retreat',
    'Mind games, hostility',
    'Leaving, accepting help, going somewhere better',
    'Secret plans, abandoning ship',
    'Feeling powerless and stuck',
    'Overactive mind, anxiety',
    'Feeling defeated, self sabotage',
    'Mentally unstable or intellectually immature, acts without thinking',
    'Fierce, determined, aggressively pursues goals',
    'Intelligent, writer, communicative yet cold - cuts through B.S.',
    'Serious, controlling, rational and mind/intellect-focused',

    'Ace of Pentacles - Financial reward, clarity of life purpose, goals',
    'Balance, multitasking',
    'Meaningful work, enjoying one’s work, suitable career',
    'Hoarding, feeling poor, holding self back out of fear',
    'Minor money troubles, health problems, feeling like an outsider',
    'Charity, accepting and giving help',
    'Patience, waiting for your plans to bear fruit',
    'Hard work, focused efforts, laying the groundwork',
    'Luxury, rest, financial and material comforts',
    'Financial success, strong business relationships',
    'Student, commitment to learning',
    'Cautious, sensible and slow to progress',
    'Healthy in body and finances, grounded and calm',
    'Enjoys the good life (food, drink and leisure), financially secure',

];