// https://daily-tarot-girl.com/tarot-card-meanings/list-of-tarot-card-meanings/
const shorts = [
    'The Fool - New beginnings, optimism, trust in life',
    'The Magician - Action, the power to manifest',
    'The High Priestess - Inaction, going within, the mystical',
    'The Empress - Abundance, nurturing, fertility, life in bloom!',
    'The Emperor - Structure, stability, rules and power',
    'The Hierophant - Institutions, tradition, society and its rules',
    'The Lovers - Sexuality, passion, choice, uniting',
    'The Chariot - Movement, progress, integration',
    'Strength - Courage, subtle power, integration of animal self',
    'The Hermit - Meditation, solitude, consciousness',
    'Wheel of Fortune - Cycles, change, ups and downs',
    'Justice - Fairness, equality, balance',
    'The Hanged Man - Surrender, new perspective, enlightenment',
    'Death - The end of something, change, the impermeability of all things',
    'Temperance - Balance, moderation, being sensible',
    'The Devil - Destructive patterns, addiction, giving away your power',
    'The Tower - Collapse of stable structures, release, sudden insight',
    'The Star - Hope, calm, a good omen!',
    'The Moon - Mystery, the subconscious, dreams',
    'The Sun - Success, happiness, all will be well',
    'Judgment - Rebirth, a new phase, inner calling',
    'The World - Completion, wholeness, attainment, celebration of life',

    'Ace of Wands - New beginnings, creative spark, fertile ideas',
    '2 - Contemplation, assessing ones life direction',
    '3 - Reaping the rewards of your efforts',
    '4 - Celebration, safety, the home',
    '5 - Competition, minor struggles or disagreements',
    '6 - Success, accolades and achievement',
    '7 - Feeling defensive and on guard',
    '8 - Speed, things manifesting quickly',
    '9 - Pessimism, gearing up for the worst',
    '10 - Feeling oppressed, exhaustion, too many responsibilities',
    'Page - newly inspired, excited about life and work',
    'Knight - An adventurous risk taker who follows his passions',
    'Queen - Confidant, focused, has zest for life',
    'King - Career focused, mature, passionate',

    'Ace of Cups - emotional fulfillment, joy',
    '2 - partnership, mutual attraction, compatibility',
    '3 - celebration, fun with friends, laughter',
    '4 - boredom, dissatisfaction with what is being offered',
    '5 - dwelling on the negative, self pity',
    '6 - sentimentality, kindness, help',
    '7 - so many choices! Indecision, getting lost in fantasy',
    '8 - abandoning something in search of something better',
    '9 - indulgence, self-satisfaction',
    '10 - emotional bliss, happiness, attainment',
    'Page - Creative, inspired, learning artistic skill',
    'Knight - Romantic, adventurous, following one’s heart',
    'Queen - Emotionally nurturing, intuitive, sensitive',
    'King - Need to acknowledge deep feelings, avoid drowning out emotions',

    'Ace of Swords - A fresh start, a sudden opportunity or idea, clarity',
    '2 - Indecision',
    '3- heartbreak, betrayal',
    '4 - meditation, rest, retreat',
    '5 - mind games, hostility',
    '6 - leaving, accepting help, going somewhere better',
    '7 - secret plans, abandoning ship',
    '8 - feeling powerless and stuck',
    '9 - Overactive mind, anxiety',
    '10 - feeling defeated, self sabotage',
    'Page - mentally unstable or intellectually immature, acts without thinking',
    'Knight - Fierce, determined, aggressively pursues goals',
    'Queen - Intelligent, writer, communicative yet cold - cuts through B.S.',
    'King - Serious, controlling, rational and mind/intellect-focused',

    'Ace of Pentacles - Financial reward, clarity of life purpose, goals',
    '2 - Balance, multitasking',
    '3 - Meaningful work, enjoying one’s work, suitable career',
    '4 - Hoarding, feeling poor, holding self back out of fear',
    '5 - Minor money troubles, health problems, feeling like an outsider',
    '6 - Charity, accepting and giving help',
    '7 - Patience, waiting for your plans to bear fruit',
    '8 - Hard work, focused efforts, laying the groundwork',
    '9 - Luxury, rest, financial and material comforts',
    '10 - Financial success, strong business relationships',
    'Page - Student, commitment to learning',
    'Knight - Cautious, sensible and slow to progress',
    'Queen - Healthy in body and finances, grounded and calm',
    'King - Enjoys the good life (food, drink and leisure), financially secure',

];