// https://blissfulexpression.com/blog/psychic-tools/tarot-cards-short-meanings/
const shorts2 = [
    'Take the risk but watch your step <-> There are things you need to address',
    'You have what you need <-> Out of touch with reality',
    'Listen to your intuition not emotion or logic <-> Something is blocking your higher self',
    'Compassion, peacekeeper <-> Domestic disharmony',
    'Discipline and obeying the rules <-> Being irresponsible',
    'Pursuit of traditional knowledge <-> Think outside the box',
    'Someone loves you, but you may want to make a different choice <-> <-> Temporary romantic breakup',
    'Get in the Drivers seat <-> Delayed journey',
    'Use honey not vinegar <-> Arguments',
    'Take time alone to think <-> Need more social interaction',
    'Things are changing fast around you <-> A setback requires you to rethink our original plan',
    'Treat people fairly and you will be treated fairly <-> A feeling of being cheated out of something',
    'A sacrifice <-> Don\'t be stubborn',
    'Accept the end of a situation <-> Baggage keeps you from moving forward',
    'Caution <-> Waste',
    'Sexual desire and passion <-> Victory over your emotions',
    'A setback causes need to rebuild <-> You need to strengthen your foundation',
    'Healing and rebirth is directly ahead <-> Lack of faith, illness',
    'Don\'t be deceived <-> Mental health issues',
    'A wonderful experience is ahead of you <-> Low energy',
    'You need to listen more <-> Don\'t run away from your feelings',
    'Freedom to choose a new path <-> Low self esteem',

    'Accept what is offered <-> Idea won\'t take hold, back to drawing board',
    'Completion of contracts and partnership commitments <-> Loss of faith',
    'Explore a new path <-> Don\'t whine or blame others',
    'Marriage or acceptance by friends and family <-> Upcoming event will need more help than anticipated',
    'Competition <-> Conflict can be beneficial',
    'Victory <-> Be patient, success may be delayed',
    'You feel defensive but you are in a strong position to confront fears and obstacles <-> Others may be intimidated by you, tone it down',
    'Making Progress on the right track <-> Things are moving forward without you, do you feel left out?',
    'Look around, protect yourself and possessions <-> Paranoia',
    'Don\'t burn out on responsibilities <-> Show appreciation in order to get more help',
    'Restless <-> Don\'t be pessimistic or a victim',
    'Moving house or job <-> Feel insecure and stuck in a situation',
    'Needing attention <-> Acts undependable , not wanting anyone to become dependent.',
    'Need to understand people first <-> In awkward situation, may be wise to retreat',

    'New love <-> Relationship is not meeting your needs',
    'Perfect understanding between two people <-> Not enough chemistry in the relationship',
    'Friendship <-> Someone is unfaithful',
    'You don\'t like your choices <-> Reason to hope',
    'Don\'t overlook opportunities <-> Need to recover from emotional wounds',
    'Happiness from someone in your past or at a distance <-> Bitter memories',
    'Need to prioritize <-> Indecision',
    'Look for greener pastures <-> Inability to leave a bad situation',
    'Satisfaction <-> Discontent, unfulfilled',
    'Domestic harmony <-> Be satisfied and stop seeking a better situation',
    'Social invitation <-> Childish behavior',
    'Romantic invitation or emotional move <-> Deception, lack of motivation and even emotional problems',
    'Queen Cups <-> Do not deny your emotions <-> Shallow behavior',
    'King Cups <-> Control your emotions <-> Being seen as untrustworthy',

    'New idea or career <-> Confusion, infatuation',
    'Set strong boundaries with others <-> Relationship can be revived',
    'Prepare for disappointment or broken heart ahead if you don\'t make changes <-> Petty quarrels',
    'Rest, do not take action at this time <-> Need for action',
    'Its not all about you, care for others <-> Backstabbing or an argument with no winner',
    'Travel <-> Delays in progress',
    'Secretive, afraid of being trapped, may take wrong action <-> Someone needs encouragement',
    'You feel trapped, you can seek help <-> Freedom will come',
    'Anxiety you imagine is worse than the reality <-> No need for change, accept your situation',
    'Betrayal or end to relationship or job but pick yourself up <-> You will get a second chance',
    'Stand your ground <-> Critical questions need to be answered',
    'Overcome fear and take action even if out of your comfort zone <-> A troublemaker',
    'Get more involved <-> Need soft understanding approach (feminine)',
    'Trying to analyze too much <-> Strict controlling behavior',

    'Financial opportunity, job or increased pay <-> Feeling of loss or actual loss',
    'Find balance <-> Need to concentrate on just one thing',
    'Recognition <-> Need to bring people together to resolve something',
    'Clinging too much (let go) <-> Feeling of jealousy',
    'Left to struggle in the cold but not alone <-> Loneliness is resolved through inner work',
    'Be generous <-> Feeling of arrogance, not needing anyone',
    'Don\'t rest on what you accomplished, still work ahead <-> Carelessness, scattered thoughts',
    'Quality is important and may be reached with learning new skills <-> Don\'t micromanage or be too nearsighted.',
    'Self Sufficiency resulting in achievement <-> Need more self discipline',
    'Mature Relationship <-> Without Enthusiasm, need more joy',
    'Focus on work and finances <-> Unrealistic expectations',
    'Good news about finances <-> Don\'t procrastinate',
    'Faithful relationship <-> Someone is a martyr',
    'Material needs are met <-> Some you know may not be trustworthy',

];