const shorts3 = [
    'fresh hope, take chances, new paths and adventures, beginnings',
    'focused, creativity, turning visions into reality, inspired actions',
    'secrets, mystery, intuition, trust yourself',
    'fertility, creation, pregnancy, abundance, good parenting',
    'respect, leadership, strategic planning, a father figure',
    'traditions, conventional expectations, conformity',
    'partnership, deep love, a choice, the strength of two together',
    'action and change, a journey, a new vehicle, vroom-vroom',
    'self-love, unconditional love, self-respect, courage',
    'go within for clarity, a quest for personal truth, spiritual illumination',
    'good fortune, a turning point, gabling, luck',
    'cause and effect, win-win solutions, the truth comes out',
    'wisdom, self sacrifice, get a different perspective',
    'big changes, endings, time to move on, rebirth, transformation',
    'balance, harmony, patience, self-control, moderation',
    'addiction, greed, envy, materialism, obsession, sexual lust',
    'unwanted change, ruin, disgrace, upheval, violence',
    'renewal, hope, inner clarity, miracles, have faith, being in the spotlight',
    'unseen problems, voluntary changes, trust your intuition',
    'material happiness, a joyous outcome, success',
    'clarity, a final decision, a wake up call, your life\'s purpose',
    'completing a goal or lesson, emigration, travel, completion',

    'new project, inspiration, the urge to create',
    'waiting for results, make a choice, travel plans',
    'teamwork, commerce, expansion, travee',
    'homecoming, celebrations, family, friends, reunion',
    'rivalry, challenges, obstacles, sport',
    'victory, award, recognition, good news, success',
    'self-defence, protect again competition',
    'speed, action, quick changes, news arrives',
    'keeping & maintaining boundaries, persistence',
    'stress, exhaustion, too many burdens',
    'an active kid, a new project or creative idea',
    'a lusty free-spirited person, creativity',
    'a feisty person, confidence, self-assurance',
    'a bold leader, power, charm, courage',

    'new baby or relationship, proposal, marriage',
    'romantic love, partnership, proposal, marriage',
    'friendship, celebrations, a circle of support',
    'apathy, feeling unfulfilled, surprise gifts',
    'loss, regret, grief, feeling abandoned or unloved',
    'nostalgia, gifts, innocence, reunions',
    'too many choices, commitment issues',
    'withdrawal, retreat, moving on, abandonment',
    'wishes come true, material abundance, good health',
    'family contentment, total love and support',
    'a studious kid, new love, volunteer work',
    'a "Princess Charming", romance, proposals',
    'a nurturing person, healing, support',
    'a supportive leader, tolerance, empathy',

    'new ideas, new conflict, surgery, mental clarity',
    'time to compromise or make a decision',
    'heartbreak, divorce, loss, depression, surgery',
    'retreat, rest, renewal, solitude, recovery',
    'bullies, theft, violence, abusive relationships',
    'a necessary transition, relocating, moving',
    'theft, betrayal, dishonesty, running away',
    'self-imposed restrictions, isolation, imprisonment',
    'nightmares, anxiety, grief, depression',
    'complete and painful ending, rock bottom',
    'a curious kid, gossip, spies, prying eyes truth',
    'a fast-talking person, lifestyle change',
    'a self sufficient person, total honesty',
    'an intentional leader, strategic thought',

    'new job, raise, promotion, investment, new income',
    'two choices, multi-tasking, weighing, many options',
    'teamwork, collaboration, skill, quality, craftsmanship',
    'greed or long-term security',
    'poverty, ill health, worry, isolation, financial loss',
    'giving or receiving help, generosity',
    'patience, hard work, delayed success, waiting',
    'mastering your craft, enjoying your employment',
    'luxury, self-sufficientce, financial gain, solo pleasures',
    'leaving legacy, retirement, inheritance',
    'a patient kid, a new job or rise, money news',
    'a reliable person, patience, hard work',
    'a resourceful person, fertility, domesticity',
    'a solid and practical leader, wise investor'
];